# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "GuillemRoca"
    groups:
      kotlin-dependencies:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "org.jetbrains.kotlin:kotlin-bom"
          - "org.jetbrains.kotlin:kotlin-gradle-plugin"
          - "org.jetbrains.kotlin:kotlin-reflect"
          - "org.jetbrains.kotlin:kotlin-test"
      minor-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "org.jetbrains.kotlin.*"
          - "org.jetbrains.kotlin:*"
