name: Android CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: kotlinUpgradeYarnLock
        run: ./gradlew kotlinUpgradeYarnLock

      - name: Build Android app
        run: ./gradlew :composeApp:assembleDebug
