name: Android, iOS and JVM CI

on: pull_request

# Cancel any current or previous job from the same PR
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: kotlinUpgradeYarnLock
        run: ./gradlew kotlinUpgradeYarnLock

      - name: Build Android app
        run: ./gradlew :composeApp:assembleDebug

  build-ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build iOS app
        run: xcodebuild -allowProvisioningUpdates -project iosApp/iosApp.xcodeproj -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' build

  build-web:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: kotlinUpgradeYarnLock
        run: ./gradlew kotlinUpgradeYarnLock

      - name: Build Web app
        run: ./gradlew :composeApp:wasmJsBrowserDevelopmentRun

  #build-jvm:
  #  runs-on: ubuntu-22.04
  #  steps:
  #    - uses: actions/checkout@v4

  #    - uses: actions/setup-java@v4
  #      with:
  #        distribution: 'zulu'
  #        java-version: 17

  #   - name: Setup Gradle
  #      uses: gradle/actions/setup-gradle@v3

  #    - name: Build desktop app
  #      run: ./gradlew :composeApp:run